config/routes.rb
Rails.application.routes.draw do
 resources :posts
 resources :projects
 get 'welcome/index' #Defining the route
 root 'welcome#index' #Setting the welocme contoller index action to the root of our app

end

app/models/post.rb
class Post < ActiveRecord::Base
	extend FriendlyId
  	friendly_id :title, use: :slugged
end

app/models/project.rb
class Project < ActiveRecord::Base
	extend FriendlyId
  	friendly_id :title, use: :slugged
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:show, :edit, :update, :destroy]
	#Assigns all posts to @posts array
	def index
		@posts = Post.all.order("created_at desc").paginate(:page => params[:page], :per_page => 2)
	end
	#Allows us to create new posts inside of our form
	def new
		@post = Post.new 
	end
	#
	def create
		@post = Post.new post_params
		if @post.save
			redirect_to @post, notice: "Hellz yeah, Oleg! Your article is successfully saved!"
		else 
			render 'new', notice: "Oh no, OIeg! I was unable to save your post."
		end
	end

	def show
	end

	def edit
	end


	def update 
		if @post.update post_params
			redirect_to @post, notice: "Huzzah! Your article was successfully saved!"
		else
			render 'edit'
		end
	end

	def destroy
		@post.destroy
		redirect_to posts_path
	end

	private
	
	def post_params
		params.require(:post).permit(:title, :content, :slug)
	end

	def find_post
		@post = Post.friendly.find(params[:id]) 
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :find_project, only: [:show, :edit, :update, :destroy]
	def index 
		@projects = Project.all.order('created_at desc').paginate(:page => params[:page], :per_page => 2)
	end 

	def new
		@project = Project.new
	end

	def create
		@project = Project.new project_params
		if @project.save
			redirect_to @project, notice: "Nice, Oleg! That project was successfully saved!"
		else
			render 'new'
		end
	end

	def show
	end

	def edit
	end

	def update
		if @project.update project_params
			redirect_to @project, notice: "Nice, Oleg! That project was successfully updated!"
		else
			render 'edit'
		end
	end

	def destroy
		@project.destroy
		redirect_to projects_path
	end
	
	private 

	def find_project
		@project = Project.friendly.find(params[:id])
	end

	def project_params
		params.require(:project).permit(:title, :description, :link, :slug)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		@posts = Post.all.limit(3).order("created_at desc")
		@projects = Project.all.limit(3).order("created_at desc")
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	class HTMLwithPygments < Redcarpet::Render::HTML
		def block_code(code, language)
			Pygments.highlight(code, lexer: language)
		end
	end
	def markdown(content)
		renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
		options = {
			autolink: true,
			no_intra_emphasis: true,
			disable_indented_code_blocks: true,
			fenced_code_blocks: true,
			lax_html_blocks: true,
			strikethrough: true, 
			superscript: true
		}
		Redcarpet::Markdown.new(renderer, options).render(content).html_safe
	end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title>MyBlogg</title>
	<link href='https://fonts.googleapis.com/css?family=Raleway:400,700' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header id="main_navigation" class="clearfix">
		<%= link_to "MyBlogg", root_path, class: "name" %> 
		<nav>
			<%= link_to "Articles", posts_path %> 
			<%= link_to "Projects", projects_path %>
			<a href="contact.html">Contact</a>
		</nav>
	</header>

	<%= yield %>


	<footer id="main_footer">
		<p class="copyright">&copy;2015 MyBlogg</p>
		<nav>
			<a href="#"><i class="fa fa-twitter"></i></a>
			<a href="#"><i class="fa fa-dribbble"></i></a>
			<a href="#"><i class="fa fa-github"></i></a>
		</nav>
	</footer>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
		<h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving:</h2>
		<ul>
			<% @post.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>

	<%= f.label :title %><br>
	<%= f.text_field :title %>

	<br>
	<br>
	
	<%= f.label :content, "Write your article here" %><br>
	<%= f.text_area :content %>

	<br>
	<br>

	<%= f.submit %>

<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1 id="page_title">Stuff I've Written</h1>

	<div id="posts_wrapper" class="skinny_wrapper">

		<% @posts.each do |post| %>
			<div class="post">
				<p class="date"><%= post.created_at.strftime('%A, %B %d') %></p>
				<h2><a href="article_show.html"><%= link_to post.title, post %></a></h2>
				<hr>
			</div>
		<% end %>
		
	</div>

<%= will_paginate @posts %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
	<header>
		<p class="date"><%= @post.created_at.strftime('%A, %B %d') %></p>
		<h1><%= @post.title %></h1>
		<hr>
	</header>
	<div id="cotent">
		<%= markdown @post.content %>
	</div>
	
	<hr>
	<div id="share_box">
		<p>Share The DO List</p>
		<a href=""><i class="fa fa-twitter"></i></a>
		<a href=""><i class="fa fa-facebook"></i></a>
		<a href=""><i class="fa fa-google-plus"></i></a>
	</div>
	
	<hr>

</div>

<%= link_to "Edit", edit_post_path(@post) %>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
	<% if @project.errors.any? %>
		<h2><%= pluralize(@project.errors.count, "error") %> prevented this project from saving:</h2>
		<ul>
			<% @project.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>

	<%= f.label :title %><br>
	<%= f.text_field :title %>

	<br>
	<br>
	
	<%= f.label :description, "Write your article here" %><br>
	<%= f.text_area :description %>

	<br>
	<br>

	<%= f.label :link %><br>
	<%= f.text_field :link %>

	<br>
	<br>

	<%= f.submit %>

<% end %>

app/views/projects/edit.html.erb
<div class="skinny_wrapper wrapper_padding">
	<h1>Edit Project</h1>
	<%= render 'form' %>
</div>

app/views/projects/index.html.erb
<h1 id="page_title">Stuff I've Built</h1>

	<div id="posts_wrapper" class="skinny_wrapper">

		<% @projects.each do |project| %>
			<div class="post">
				<p class="date"><%= project.created_at.strftime('%A, %B %d') %></p>
				<h2><a href="article_show.html"><%= link_to project.title, project %></a></h2>
				<hr>
			</div>
		<% end %>
		
	</div>

app/views/projects/new.html.erb
<div class="skinny_wrapper wrapper_padding">
	<h1>New Project</h1>
	<%= render 'form' %>
</div>

app/views/projects/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
	<header>
		<p class="date"><%= @project.created_at.strftime('%A, %B %d') %></p>
		<h1><%= @project.title %></h1>
		<hr>
	</header>
	<div id="cotent">
		<%= markdown @project.description %>

		<div class="button_wrapper">
			<a href="<%= @project.link %>" class="project_button" target="_blank">Visit a <%= @project.title %></a>
		</div>
	</div>
	
	<%= link_to "Edit", edit_project_path(@project) %>
	<%= link_to "Delete", project_path(@project), method: :delete, data: {confirm: "Are you sure?"} %>

	<hr>
</div>

app/views/welcome/index.html.erb
<div class="wrapper wrapper_padding clearfix">
		<div class="col-1 about homepage_content">
			<h2>About</h2>
			<hr>
			<p>Tattooed direct trade crucifix cliche Brooklyn banh mi flannel.</p>
			<p>Cred Truffaut mumblecore, hashtag lo-fi trust fund street art selfies fixie <a href="#">Vice</a> pour-over deep v freegan Etsy. Street art distillery raw denim, <a href="#">High Life</a> tofu fixie cronut tilde Intelligentsia.</p>
			<p>Flexitarian chillwave four loko health goth Godard, polaroid photo booth jean shorts <a href="#">Portland</a>.</p>
		</div>
		<div class="col-2 homepage_content">
			<h2>Stuff I've Written</h2>
			<hr>
			<% @posts.each do |post| %>
				<h3><a href="article_show.html"><%= link_to post.title, post %></a></h3>
				<p class="date"><%= post.created_at.strftime("%A, %b %d") %></p>
			<% end %>
		</div>
		<div class="col-3 homepage_content">
			<h2>Stuff I've Built</h2>
			<hr>
			<% @projects.each do |project| %>
				<h3><a href="article_show.html"><%= link_to project.title, project %></a></h3>
				<p class="date"><%= project.created_at.strftime("%A, %b %d") %></p>
			<% end %>
		</div>
	</div>